Cleanup Choco Install Process
isaacrlevin/presencelight pull request #526
Opened 2021-12-20 23:15 UTC by isaacrlevin

- Delete unneeded file
- Add settings backup step to upgrade

2021-12-20 23:15 UTC, isaacrlevin commented
@gep13 is this going to work? ;)

2021-12-21 10:45 UTC, gep13 commented
@isaacrlevin I have added a comment here https://github.com/isaacrlevin/presencelight/issues/515#issuecomment-998672087 to talk about this, as I don't think that some of the work here is needed.

2021-12-21 10:48 UTC, gep13 requested changes

2021-12-21 10:48 UTC, gep13 commented on .chocolatey/tools/ChocolateyBeforeModify.ps1
> +$InstallDir = Join-Path $env:APPDATA 'PresenceLight'
If you move forward with this, this doesn't take into account the ability to configure that installation directory via a Package Parameter, which is done here:

https://github.com/isaacrlevin/presencelight/blob/main/.chocolatey/tools/ChocolateyInstall.ps1#L41

2021-12-21 10:48 UTC, gep13 commented on .chocolatey/tools/ChocolateyBeforeModify.ps1
> +$SettingsPath = Join-Path $InstallDir 'appsettings.json'
Based on the testing that I did, the custom information was being added to a `settings.json` file, not the `appsettings.json` file.

2021-12-21 10:48 UTC, gep13 commented on .chocolatey/tools/ChocolateyInstall.ps1
> +    Copy-Item -Destination $InstallDir -PassThru | Rename-Item -NewName  'appsettings.json'
Same comment here, it was the `settings.json` file that stored the custom settings from the UI.  At least in the test that I did.

2021-12-21 18:57 UTC, isaacrlevin commented
Closing as it seems this is not needed

2021-12-21 18:57 UTC, closed without merging